name: "Google Reports"
on:
  schedule:
    - cron: '0 5,6,18,19 * * *'
  push:
    branches:
      - main

jobs:
  update-data:
    name: Google Reports
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: browser-actions/setup-firefox@latest 
      - run: firefox --version
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: "Install Packages"
        run: |
          install.packages('tidyverse')
          install.packages('pacman')
        shell: Rscript {0}
      - name: "Script - Google"
        run: Rscript 'selenium.R'
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Google Reports
